### ISSUE TITLE
problem：busy timeout[0],(60s):'RootDomainUserClient'...

### ISSUE THREAD

**Issue by kaienli** [alexandred/VoodooI2C#97]
Use v2.1.2 stop at "busy timeout[0],(60s):'RootDomainUserClient'..."

**Comment by bugprogrammer** [comment]
I have the same problem

**Comment by asoco** [comment]
Same

**Comment by acai66** [comment]
remove AppleIntelLpssI2C.kext and AppleIntelLpssI2CController.kext from s/l/e/

**Comment by Nihhaar** [comment]
@acai66 I am already using @coolstar patches (Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar), but still have this problem.

**Comment by kaienli** [comment]
remove LpssI2C already still have this problem

**Comment by kaienli** [comment]
> 
> 
> remove AppleIntelLpssI2C.kext and AppleIntelLpssI2CController.kext from s/l/e/

still have this problem

**Comment by xuhadixu** [comment]
because of this driver breaks laptops - be careful!

**Comment by Nihhaar** [comment]
@xuhadixu what?

**Comment by xuhadixu** [comment]
/ Linux equivalent of FTE_i2c_write_cmd function
 IOReturn VoodooI2CFTETouchpadDriver::write_FTE_cmd(UInt16 reg, UInt16 cmd) {
     UInt16 buffer[] {
         reg,
         cmd
     };
     IOReturn retVal = kIOReturnSuccess;
     retVal = api->writeI2C(reinterpret_cast<UInt8*>(&buffer), sizeof(buffer));
     return retVal;
 }
 
 IOReturn VoodooI2CFTETouchpadDriver::message(UInt32 type, IOService* provider, void* argument)
 {
     switch (type)
     {
         case kKeyboardGetTouchStatus:
         {
 #if DEBUG
             IOLog("%s::getEnabledStatus = %s\n", getName(), ignoreall ? "false" : "true");
 #endif

**Comment by cookievu** [comment]
Is there a way to fix it? Waiting for patches?

**Comment by asoco** [comment]
Yep, just wait. I think it will take a couple of days

**Comment by pusolexuze** [comment]
Автор кидает людей

**Comment by Ressetkk** [comment]
> because of this driver breaks laptops - be careful!

The only thing that's broken is you.
/offtopic
Yep, there is an issue with the new version. It also happens to me, where the `2.1.1` works just fine.

**Comment by vcreatyv** [comment]
If your hexadecimal pin number is greater than `0x2F` then proceed to the next step.
 - If IOInterruptSpecifiers is not present then you have completed this guide and you can continue with installing the kexts

 ##### Step 2a: Ensuring your device is GPIO-pinned
 - If IOInterruptSpecifiers is present, then expand this property and note the first two hexadecimal digits of the value shown. This is your APIC Pin number in hexadecimal notation. Note this down as 0xyy, where yy is replaced by these first two digits.

 You have arrived at this step because Apple's drivers do not support APIC pins greater than `0x2F` (and it would be very difficult to make them support them). In this case, we thus make use of a kext called [VoodooGPIO](https://github.com/coolstar/VoodooGPIO) which comes bundled with all copies of VoodooI2C. VoodooGPIO allows us to get around this limitation of macOS by using GPIO interrupts instead which most new machines support.
 If your APIC Pin Number is less than or equal to 0x2f, then you have completed this guide and you can proceed with the installation of the kexts.

 We must first determine whether or not your device is properly configured to support GPIO pins. Search for your device ACPI ID in your DSDT until you reach its device entry. Look for a `Name` that looks like this:
 If your APIC Pin Number is outside the range 05x-0x77, then VoodooI2C is not the correct driver for your touchpad. You are advised to seek support in the relevant forums or usergroups.

 If your APIC Pin Number is between 0x5c and 0x77, then calculate the corresponding GPIO Pin Number as follows (you can use Calculator.app for hexadecimal conversions and calculations):

**Comment by vcreatyv** [comment]
https://www.youtube.com/watch?v=SVlP4mW2ERE

**Comment by vcreatyv** [comment]
interesting Аpple approves this driver, it is necessary to ask

**Comment by dedicahyadi** [comment]
aha, same problem

**Comment by dedicahyadi** [comment]
but, we thank to Alexandred for all support

**Comment by alexandred** [comment]
I believe the issue has been identified and will be fixed in a new release later today.

**Comment by dedicahyadi** [comment]
> I believe the issue has been identified and will be fixed in a new release later today.

thanks

**Comment by cookievu** [comment]
> I believe the issue has been identified and will be fixed in a new release later today.

Thanks

**Comment by alexandred** [comment]
Fixed in v2.1.3.
